USE [master]
GO
/****** Object:  Database [KomodoTest]    Script Date: 11/25/2016 7:41:42 PM ******/
CREATE DATABASE [KomodoTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KomodoTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\KomodoTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KomodoTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\KomodoTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KomodoTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KomodoTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KomodoTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KomodoTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KomodoTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KomodoTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [KomodoTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [KomodoTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KomodoTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KomodoTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KomodoTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KomodoTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KomodoTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KomodoTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KomodoTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KomodoTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [KomodoTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KomodoTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KomodoTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KomodoTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KomodoTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KomodoTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KomodoTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KomodoTest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [KomodoTest] SET  MULTI_USER 
GO
ALTER DATABASE [KomodoTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KomodoTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KomodoTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KomodoTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KomodoTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KomodoTest] SET QUERY_STORE = OFF
GO
USE [KomodoTest]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [KomodoTest]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 11/25/2016 7:41:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[Phone] [varchar](50) NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_LastName]  DEFAULT ('') FOR [LastName]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_FirstName]  DEFAULT ('') FOR [FirstName]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Phone]  DEFAULT ('') FOR [Phone]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Active]  DEFAULT ((1)) FOR [Active]
GO
USE [master]
GO
ALTER DATABASE [KomodoTest] SET  READ_WRITE 
GO

